FROM quay.io/keycloak/keycloak:21.0.1

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=123456

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["-b", "auth-server:8081"]
CMD ["start-dev"]

EXPOSE 8080