version: '3'

services:
  keycloak-sso:
    image: keycloak-sso
    container_name: keycloak-sso
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=123456
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak-db
      - DB_USER=vinicius
      - DB_PASSWORD=123456
    ports:
      - "8080:8080"
    networks:
      keycloak-network:
        ipv4_address: 172.21.0.2
    volumes:
      - volumes-data:/opt/jboss/keycloak/standalone/data
      - ./oidc/realm-export.json:/tmp/realm-export.json

  keycloak-db:
    image: postgres
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak-db
      - POSTGRES_USER=vinicius
      - POSTGRES_PASSWORD=123456
      - POSTGRES_PORT=5433
    networks:
      keycloak-network:
        ipv4_address: 172.21.0.3
    depends_on:
      - auth-db
    volumes:
      - db-data:/var/lib/postgresql/keycloak-db/data

  auth-server:
    image: auth-server
    container_name: auth-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.21.0.4:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=vinicius
      - SPRING_DATASOURCE_PASSWORD=123456
      - KEYCLOAK_BASE_URL=http://172.21.0.2:8080
      - KEYCLOAK_REALM=craftzn
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      keycloak-network:
        ipv4_address: 172.21.0.4
    depends_on:
      - keycloak-sso
      - keycloak-db
      - auth-db

  auth-db:
    image: postgres
    container_name: auth-db
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=vinicius
      - POSTGRES_PASSWORD=123456
      - POSTGRES_PORT=5432
    networks:
      keycloak-network:
        ipv4_address: 172.21.0.5
    depends_on:
      - keycloak-sso
    volumes:
      - db-data:/var/lib/postgresql/auth-db/data

volumes:
  volumes-data:
  db-data:

networks:
  keycloak-network:
    external: true