server:
  port: 8081

keycloak:
  realm: craftzn
  resource: auth-server
  public-client: true
  hostname-url: http://keycloak-sso:8080
  hostname-strict-https: false
  hostname-strict-backchannel: true
  ssl-required: none
  statistics-enable: true
  health-enable: true
  spi-connections-http-client-default:disable-trust-manager: false

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-server
            client-name: auth-server
            authorization-grant-type: authorization_code
            redirect-uri: http://auth-server:8081/login/oauth2/code/auth-server
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak-sso:8080/realms/craftzn
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: http://keycloak-sso:8080/realms/craftzn

  profiles:
    active: dev