server:
  port: 8081

spring:
  application:
    name: auth-server
  profiles:
    active: develop
  config:
    import: optional:configserver:http://172.21.0.6:8888/
    name: auth-server

feature:
  upload_scripts: enabled