server:port: 8081

keycloak:
  realm: craftzn
  resource: auth-server
  public-client: true
  hostname-url: http://keycloak-sso:8080
  hostname-strict-https: false
  hostname-strict-backchannel: false
  ssl-required: none
  statistics-enable: true
  health-enable: true
  spi-connections-http-client-default:
    disable-trust-manager: false

spring:
  profiles:active: dev

  security:
    oauth2:
      resourceserver:
        jwt:issuer-uri: http://keycloak-sso:8080/realms/craftzn
      client:
        registration:
          keycloak:
            client-id: auth-server
            client-name: auth-server
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/auth-server
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak-sso:8080/realms/craftzn
            user-name-attribute: preferred_username